[project]
name = "sonos-controller"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mypy>=1.19.1",
    "ruff>=0.14.13",
    "soco>=0.30.14",
]
